services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
#      - /etc/smart_drivedb.h:/etc/smart_drivedb.h:ro
      - ./smart_drivedb.h:/etc/smart_drivedb.h:ro
    devices:
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
    restart: unless-stopped
    networks:
      - scrutiny_net

networks:
  scrutiny_net:
    driver: bridge
    name: scrutiny_net
    ipam:
      config:
        - subnet: 172.29.0.0/24
